using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.1433
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2008 GeNova Project")]
[assembly: AssemblyTitleAttribute("CoreBusiness")]
[assembly: AssemblyDescriptionAttribute("GeNova Project Web CoreBusiness Objects.")]
[assembly: AssemblyCompanyAttribute("GeNova Project")]
[assembly: AssemblyProductAttribute("GeNova.Web")]

