CREATE TABLE GeNova_Web_Usuario (
  IdUsuario INT NOT NULL AUTO_INCREMENT,
  Login VARCHAR(15) NOT NULL,
  Senha VARCHAR(50) NOT NULL,
  Tipo SMALLINT NOT NULL,
  Avatar VARCHAR(30) NULL,
  PRIMARY KEY (IdUsuario),
  UNIQUE (Login)
) ENGINE=INNODB;

CREATE TABLE GeNova_Web_Pessoa (
  IdPessoa INT NOT NULL AUTO_INCREMENT,
  IdUsuario INT NOT NULL,
  Nome VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Sexo CHAR NOT NULL,
  DataNascimento DATE NOT NULL,
  PRIMARY KEY (IdPessoa),
  UNIQUE (Nome),
  CONSTRAINT FK_Pessoa_IdUsuario FOREIGN KEY (IdUsuario) REFERENCES GeNova_Web_Usuario(IdUsuario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE GeNova_Union_UsuarioConta (
  IdUsuarioConta INT NOT NULL AUTO_INCREMENT,
  IdGeNovaWebUsuario INT NOT NULL,
  IdGeNovaUsuario INT NOT NULL,
  PRIMARY KEY (IdUsuarioConta),
  CONSTRAINT FK_UsuarioConta_IdGeNovaWebUsuario FOREIGN KEY (IdGeNovaWebUsuario) REFERENCES GeNova_Web_Usuario(IdUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_UsuarioConta_IdGeNovaUsuario FOREIGN KEY (IdGeNovaUsuario) REFERENCES GeNova_Usuario(IdUsuario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;